resources:
- name: minio-s3
  type: s3
  source:
    regexp: example-file-(.*).txt
    endpoint: http://10.244.0.6:9000 # work out how to configure this per-worker
    bucket: minio-example-bucket
    access_key_id: [your key ID]
    secret_access_key: [your secret access key]
    disable_ssl: true

jobs:
- name: minio-s3-write-it-out
  plan:
  - task: cat-example-file
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: bash
        args:
        - -c
        - echo "This is an example file, created $(date)" > file-to-upload/example-file-1.txt
      outputs:
        - name: file-to-upload
  - put: minio-s3
    params:
      file: file-to-upload/example-file-*

- name: minio-s3-read-it-out
  plan:
  - get: minio-s3
  - task: cat-example-file
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      inputs:
      - name: minio-s3
      run:
        path: bash
        args:
        - -c
        - cat minio-s3/example-file-*
